### ISSUE TITLE
error for linky home assistant

### ISSUE THREAD

**Issue by thetux07** [Pirionfr/Home-AssistantConfig#3]
hello i have a probleme with your custom component,
can you help me ?

`Error while setting up platform linky_custom
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/linky_custom/sensor.py", line 59, in setup_platform
    linky_data.update()
  File "/config/custom_components/linky_custom/sensor.py", line 212, in update
    self._fetch_data()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 240, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/linky_custom/sensor.py", line 199, in _fetch_data
    (today - relativedelta(months=12)))['data']:
  File "/usr/local/lib/python3.7/site-packages/pylinky/client.py", line 193, in get_data_per_period
    """Get the latest data from Enedis."""
  File "/usr/local/lib/python3.7/site-packages/pylinky/client.py", line 130, in _get_data
pylinky.exceptions.PyLinkyEnedisException: Enedis.fr answered with an error: {'etat': {'valeur': 'erreur'}}`

thank you
regards

**Comment by thetux07** [comment]
i have shearch for resolution, i have download pylinky and hae madec ommand python3 pylinky -m -u email@adress -p P@ssword and i have full information for my consuption but with custom_component i have error :( can you help me ?
thank you

**Comment by deionalims** [comment]
Hello.
I have the same issue. I looked at the code and the error is triggered when it tries to compare the consumption of the same month last year. 
Like me you probably have your linky account since less than a year. Therefore when it tries to get the data from last year it gets `{'etat': {'valeur': 'erreur'}}`.

I could try to find a workaround but I am not a python expert so I'd rather the author of the component to have a look.

**Comment by thetux07** [comment]
Ok thank you
Effctively, i Don’t have entire year because it’s a new house ! A devellopper can corrected this ?
Thank you

**Comment by thetux07** [comment]
hello,
i have resolve my probleme 
the problem was that I did not have 12 months of history, I change the value month = 12 to a lower value and it's ok,
